name: photofilters_example
description: Demonstrates how to use the photofilters plugin.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  path_provider: ^2.0.15
  photofilters:
    path: ../
  path: ^1.8.3
  image: ^4.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/gifloader.gif
    - assets/images/adjust.png
    - assets/images/sun.png
    - assets/images/adjust.png
    - assets/fonts/Yekan.ttf

  fonts:
    - family: Yekan
      fonts:
        - asset: assets/fonts/Yekan.ttf